version: '3'
volumes:
  mysql-data:
networks:
  fitcal_network:
    external: true
services:
    fitcal-backend:
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      ports: 
        - 8080:8080
      depends_on:
        - fitcal-db
      tty: true
      restart: always
      networks:
        - fitcal_network 
    fitcal-db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'fitcal'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'fitcal'
        # You can use whatever password you like
        MYSQL_PASSWORD: 'root'
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        # <Port exposed> : <MySQL Port running inside container>
        - '3306:3306'
        # Where our data will be persisted
      networks:
        - fitcal_network 
