name: Go Tests

on:
  push:
    branches:
      - main
      - 'feature/**'

  pull_request:
    types:
      - opened
      - reopened
      - review_request
      - edited
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up environment
      run: |
        export GOROOT=$(go env GOROOT)
        export PATH=$PATH:$GOROOT/bin

    - name: Run tests
      run: |
        cd src
        go version
        go get ./...
        go test ./...